/**
 * Schwarzschild LUT runtime sampler (M8-05, BH-164).
 *
 * ROLE (LUT_BACKEND_SPEC §3/§9/§15): the optimized production backend's
 * data plane. This module owns everything about turning a validated family
 * into per-ray answers; the renderer (M8-06) consumes it instead of the RK4
 * integrator for representable rays. It never renders and never integrates:
 * representable rays are answered from tables generated by the validated
 * binary64 solver; anything else is an EXPLICIT fallback-numerical
 * resolution so the numerical backend can take over — no clamping a ray
 * into a plausible-looking wrong answer.
 *
 * CLASSIFICATION IS ANALYTIC AND NEVER INTERPOLATED (ADR §6): captured vs
 * escaped follows b <=> b_c exactly. The tables carry trajectory SHAPE;
 * class membership cannot be blurred by filtering because it is decided
 * before any texel is read.
 *
 * SHARED SPAN CONTRACT: the generator resamples every column onto one
 * storedSpanRg grid (manifest domain), so bilinear filtering across
 * neighboring columns is well-defined in BOTH axes. Columns whose real
 * data end short of the shared span are clamp-extended with their terminal
 * radius; consumers only solve inside [rMin, observer envelope], which lies
 * within real data (`withinRealData` reports the boundary truthfully).
 *
 * WEBGL2 TRUTHFULNESS (ADR §9): half-float formats are core-filterable in
 * WebGL2; 32F formats require OES_texture_float_linear. The renderer must
 * prove that extension before sampling a 32F family linearly — reported,
 * never guessed.
 */

import { decodeTexture } from '../../../../tools/generate-luts/encode.js';
import { xToU } from './domain.js';
import type {
  LutAuxDomain,
  LutAxisMapping,
  LutManifest,
  LutManifestRejectReason,
  LutTextureFormat,
  LutTextureEntry,
  LutTrajectoryDomain
} from './types.js';
import { verifyAssetChecksum } from './validate.js';

// ---------------------------------------------------------------------------
// Loading
// ---------------------------------------------------------------------------

/** Byte provider: maps an asset filename to its raw bytes (injectable for tests). */
export type LutAssetSource = ReadonlyMap<string, Uint8Array>;

export type LutRuntimeFailureReason =
  | LutManifestRejectReason
  | 'missing-stored-span'
  | 'asset-bytes-missing'
  | 'asset-byte-length-mismatch'
  | 'asset-checksum-mismatch';

export type LutLoadResult =
  | { readonly ok: true; readonly family: LutFamilyRuntime }
  | { readonly ok: false; readonly reason: LutRuntimeFailureReason; readonly detail: string };

export interface LutFamilyRuntime {
  readonly manifest: LutManifest;
  /** Decoded radii grid, row-major [row * width + column]. */
  readonly trajectory: Float64Array;
  /** Decoded aux texels, [column * 4] = [nR, nT, dataEndArc, psiApsis]. */
  readonly aux: Float64Array;
}

interface ResolvedTextures {
  readonly manifest: LutManifest;
  readonly trajectoryEntry: LutTextureEntry & { domain: LutTrajectoryDomain };
  readonly auxEntry: LutTextureEntry & { domain: LutAuxDomain };
}

function resolveTextures(manifest: LutManifest): ResolvedTextures | null {
  const traj = manifest.textures.find((t) => t.id === 'trajectory');
  const aux = manifest.textures.find((t) => t.id === 'aux');
  if (
    traj === undefined ||
    aux === undefined ||
    traj.domain.kind !== 'trajectory' ||
    aux.domain.kind !== 'aux'
  ) {
    return null;
  }
  return {
    manifest,
    trajectoryEntry: traj as LutTextureEntry & { domain: LutTrajectoryDomain },
    auxEntry: aux as LutTextureEntry & { domain: LutAuxDomain }
  };
}

function failLoad(
  reason: LutRuntimeFailureReason,
  detail: string
): { readonly ok: false; readonly reason: LutRuntimeFailureReason; readonly detail: string } {
  return { ok: false, reason, detail };
}

/**
 * Validates the manifest structure and verifies every declared asset against
 * its checksum and byte length, then decodes both texel grids.
 *
 * `manifestJson` arrives pre-parsed: fetch/JSON.parse stay with the caller so
 * environments without fetch (unit tests) can inject bytes directly.
 */
export async function loadLutFamily(
  manifestJson: unknown,
  assets: LutAssetSource
): Promise<LutLoadResult> {
  const validated = await Promise.resolve().then(() => import('./validate.js'));
  const result = validated.validateLutManifest(manifestJson);
  if (!result.ok) return failLoad(result.reason, result.detail);

  const textures = resolveTextures(result.manifest);
  if (textures === null) {
    return failLoad('bad-texture-set', 'manifest lacks trajectory/aux entries');
  }
  const span = textures.trajectoryEntry.domain.storedSpanRg;
  if (span === undefined || !(span > 0)) {
    return failLoad(
      'missing-stored-span',
      'trajectory domain lacks storedSpanRg (pre-M8-05 family is not runtime-samplable)'
    );
  }

  const decoded: Float64Array[] = [];
  for (const entry of [textures.trajectoryEntry, textures.auxEntry] as const) {
    const bytes = assets.get(entry.file);
    if (bytes === undefined) {
      return failLoad('asset-bytes-missing', entry.file);
    }
    if (bytes.byteLength !== entry.byteLength) {
      return failLoad(
        'asset-byte-length-mismatch',
        `${entry.file}: ${bytes.byteLength} bytes on disk vs ${entry.byteLength} declared`
      );
    }
    if (!(await verifyAssetChecksum(bytes, entry.sha256))) {
      return failLoad('asset-checksum-mismatch', `${entry.file} failed SHA-256 verification`);
    }
    decoded.push(decodeTexture(bytes, entry.format));
  }

  return {
    ok: true,
    family: {
      manifest: result.manifest,
      trajectory: decoded[0]!,
      aux: decoded[1]!
    }
  };
}

// ---------------------------------------------------------------------------
// WebGL2 capability truth
// ---------------------------------------------------------------------------

export type WebGL2FilterableStatus =
  | { readonly filterable: true }
  | { readonly filterable: false; readonly extensionRequired: 'OES_texture_float_linear' };

/** Formats texture-filterable in CORE WebGL2 (GLES 3.0 table 3.13). */
const WEBGL2_CORE_FILTERABLE: ReadonlySet<string> = new Set(['r16f', 'rg16f', 'rgba16f']);

/**
 * Core WebGL2 marks 16F formats texture-filterable; 32F formats are not:
 * they need OES_texture_float_linear. The runtime REQUIRES linear
 * interpolation, so a 32F family under WebGL2 must either prove the
 * extension or fall back to numerical.
 */
export function formatWebGL2Status(format: LutTextureFormat): WebGL2FilterableStatus {
  if (WEBGL2_CORE_FILTERABLE.has(format)) return { filterable: true };
  return { filterable: false, extensionRequired: 'OES_texture_float_linear' };
}

// ---------------------------------------------------------------------------
// Sampler
// ---------------------------------------------------------------------------

export type FallbackReason = 'x-out-of-domain-low' | 'x-out-of-domain-high' | 'hybrid-band-winding';

export type RayResolution =
  | {
      readonly status: 'captured' | 'escaped';
      /** Normalized impact parameter b/b_c. */
      readonly x: number;
      /** Texture u coordinate driving the column-pair blend. */
      readonly u: number;
      readonly columns: { readonly i0: number; readonly i1: number; readonly wx: number };
    }
  | {
      readonly status: 'fallback-numerical';
      readonly reason: FallbackReason;
      readonly x: number;
    };

const AUX_STRIDE = 4;

export class LutSampler {
  readonly width: number;
  readonly height: number;
  readonly storedSpan: number;
  private readonly axis: LutAxisMapping['uBreakpoints'] extends never ? never : LutAxisMapping;
  private readonly xMax: number;

  constructor(private readonly family: LutFamilyRuntime) {
    const resolved = resolveTextures(family.manifest);
    if (resolved === null || resolved.trajectoryEntry.domain.storedSpanRg === undefined) {
      throw new TypeError('LutSampler: family was not produced/loaded through loadLutFamily');
    }
    this.axis = resolved.trajectoryEntry.domain.axisX;
    this.width = resolved.trajectoryEntry.width;
    this.height = resolved.trajectoryEntry.height;
    this.storedSpan = resolved.trajectoryEntry.domain.storedSpanRg;
    this.xMax = this.axis.xKnots[3]!;
  }

  // --- diagnostics ---------------------------------------------------------

  diagnostics(): Record<string, unknown> {
    const m = this.family.manifest;
    const formats = m.textures.map((t) => t.format);
    return {
      family: m.family,
      schemaVersion: m.schemaVersion,
      generatorCommit: `${m.generatorCommit.slice(0, 10)}${m.generatorCommit.length > 10 ? '…' : ''}`,
      dimensions: `${this.width}x${this.height}`,
      trajectoryFormat: formats[0] ?? null,
      auxFormat: formats[1] ?? null,
      storedSpanRad: Number(this.storedSpan.toFixed(6)),
      psiMaxRad: (m.textures[0]?.domain as LutTrajectoryDomain | undefined)?.psiMax ?? null,
      hybridBandHalfWidthX: m.hybridBandHalfWidthX,
      escapeRadiusRg: m.physics.escapeRadiusRg,
      validation: m.validation,
      webgl2LinearFilterable: formats.every(
        (f) => f !== undefined && formatWebGL2Status(f).filterable
      )
    };
  }

  // --- classification (analytic; never interpolated) -----------------------

  /**
   * Resolves one ray of conserved impact parameter `b` (r_g). Classification
   * uses the analytic boundary ONLY; table texels shape answers later but
   * never decide class membership.
   */
  resolveRay(b: number): RayResolution {
    if (!Number.isFinite(b) || b < 0) {
      return { status: 'fallback-numerical', reason: 'x-out-of-domain-low', x: NaN };
    }
    const bc = this.family.manifest.physics.bCriticalRg;
    const x = b / bc;
    if (x > this.xMax) {
      return { status: 'fallback-numerical', reason: 'x-out-of-domain-high', x };
    }
    const band = this.family.manifest.hybridBandHalfWidthX;
    if (band > 0 && Math.abs(x - 1) <= band) {
      // Winding may exceed the tabulated budget inside the band: route to
      // numerical rather than clamp an under-resolved spiral (ADR §6).
      return { status: 'fallback-numerical', reason: 'hybrid-band-winding', x };
    }
    return {
      status: b < bc ? 'captured' : 'escaped',
      x,
      u: xToU(x, this.axis),
      columns: this.columnPair(x)
    };
  }

  private columnPair(x: number): { i0: number; i1: number; wx: number } {
    const u = xToU(x, this.axis);
    const fi = u * this.width - 0.5; // texel-center convention (validated)
    const i0 = Math.min(this.width - 1, Math.max(0, Math.floor(fi)));
    const i1 = Math.min(this.width - 1, i0 + 1);
    return { i0, i1, wx: Math.min(1, Math.max(0, fi - i0)) };
  }

  private clampPair(x: number): { i0: number; i1: number; wx: number } {
    const xx = Number.isFinite(x) ? Math.min(Math.max(x, 0), this.xMax) : 0;
    return this.columnPair(xx);
  }

  // --- shape queries (bilinear across the shared-span grid) ----------------

  /** Bilinear radius at normalized impact `x` and folded row `psiRow`. */
  radiusAt(x: number, psiRow: number): number {
    const { i0, i1, wx } = this.clampPair(x);
    const fy = (psiRow / this.storedSpan) * this.height - 0.5;
    const j0 = Math.min(this.height - 1, Math.max(0, Math.floor(fy)));
    const j1 = Math.min(this.height - 1, j0 + 1);
    const wy = Math.min(1, Math.max(0, fy - j0));
    const t = this.family.trajectory;
    const w = this.width;
    const top = t[j0 * w + i0]! * (1 - wx) + t[j0 * w + i1]! * wx;
    const bottom = t[j1 * w + i0]! * (1 - wx) + t[j1 * w + i1]! * wx;
    return top * (1 - wy) + bottom * wy;
  }

  /** Terminal tetrad components [nR, nT], blended across the column pair. */
  terminalDirection(x: number): readonly [number, number] {
    const { i0, i1, wx } = this.clampPair(x);
    const a = this.family.aux;
    return [
      a[i0 * AUX_STRIDE]! * (1 - wx) + a[i1 * AUX_STRIDE]! * wx,
      a[i0 * AUX_STRIDE + 1]! * (1 - wx) + a[i1 * AUX_STRIDE + 1]! * wx
    ];
  }

  /** Apsis azimuth (launch frame) blended at x; NaN when captured sentinel. */
  psiApsisAt(x: number): number {
    const { i0, i1, wx } = this.clampPair(x);
    const a = this.family.aux;
    const va = a[i0 * AUX_STRIDE + 3]!;
    const vb = a[i1 * AUX_STRIDE + 3]!;
    if (va < 0 || vb < 0) return NaN;
    return va * (1 - wx) + vb * wx;
  }

  /**
   * True when both bracketing columns carry REAL (non-clamp-padded) data at
   * `psiRow`: the folded azimuth lies within each column's physical arc.
   * Boundary semantics belong to callers; this only separates ordinary
   * values from padded continuation.
   */
  withinRealData(x: number, psiRow: number): boolean {
    const { i0, i1 } = this.clampPair(x);
    const a = this.family.aux;
    return psiRow <= a[i0 * AUX_STRIDE + 2]! && psiRow <= a[i1 * AUX_STRIDE + 2]!;
  }

  /**
   * Launch-row solve: folded azimuth where the blended table crosses
   * `radiusRg` on the monotone outbound segment. Fold symmetry makes the
   * SAME row locate the inbound launch point (phi_launch = psiApsis - row).
   * Returns NaN when no solution exists inside the table (caller owns the
   * fallback decision).
   */
  launchRow(x: number, radiusRg: number): number {
    const { i0, i1, wx } = this.clampPair(x);
    const t = this.family.trajectory;
    const w = this.width;
    let prevA = t[i0]!;
    let prevB = t[i1]!;
    for (let j = 1; j < this.height; j += 1) {
      const curA = t[j * w + i0]!;
      const curB = t[j * w + i1]!;
      const prev = prevA * (1 - wx) + prevB * wx;
      const cur = curA * (1 - wx) + curB * wx;
      if (cur >= prev && prev <= radiusRg && radiusRg <= cur && cur > prev) {
        const f = (radiusRg - prev) / (cur - prev);
        const rowFloatIndex = j - 1 + f;
        return ((rowFloatIndex + 0.5) / this.height) * this.storedSpan;
      }
      prevA = curA;
      prevB = curB;
    }
    return NaN;
  }
}
